config/routes.rb
Rails.application.routes.draw do
  root to: "projects#index"
  
  get '/signup', to: 'users#new'
  get '/sign_in', to: 'sessions#new'
  post '/sign_in', to: 'sessions#create'
  get '/sign_out', to: 'sessions#destroy'
  
  resources :projects
  
  resources :tickets do
    resources :comments, only: [:create, :edit, :update, :destroy]
  end
  
  resources :tags, only: [:index, :new, :edit, :create, :update, :destroy]
  
  resources :users, only: [:index, :create] 
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  STATUSES = %w(new blocked in_progress fixed)
  
  scope :open, -> { where("status != ?", "fixed") }
  
  validates :name, presence: true
  validates :status, inclusion: { in: STATUSES }
  validates :project_id, presence: true
  
  belongs_to :project
  belongs_to :creator, foreign_key: 'user_id', class_name: "User" #creator is the owner of the ticket
  belongs_to :assignee, class_name: "User"
  
  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings
  has_many :comments, dependent: :destroy
  
  def self.search_by_name_or_description(search_term)
    # use of %: WHERE LIKE '%or%':	Finds any values that have "or" in any position
    where("LOWER(tickets.name) LIKE ? or LOWER(tickets.body) LIKE ?", "%#{search_term.downcase}%", "%#{search_term.downcase}%")
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_ticket, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:show, :index]
  
  def index
    @tickets = Ticket.all
    with_status_tag_search
  end
  
  def show
    @comment = Comment.new
  end
  
  def new
    @ticket = Ticket.new
  end
  
  def create
    @ticket = Ticket.new(ticket_params.merge!(creator: current_user))
    
    if @ticket.save
      redirect_to @ticket
      flash[:success] = "Ticket was successfully created."
    else
      render :new
    end
  end
  
  def edit
  end
  
  def update
    if @ticket.update(ticket_params)
      redirect_to @ticket
      flash[:success] = "Ticket was successfully updated.."
    else
      render :edit
    end
  end
  
  def destroy
    @ticket.destroy
    redirect_to tickets_path
    flash[:success] = "Ticket was successfully deleted."
  end
  
  private
  
  def set_ticket
    @ticket = Ticket.find(params[:id])
  end
  
  def ticket_params
    params.require(:ticket).permit(:name, :body, :status, :project_id, :assignee_id, tag_ids: [])
  end
  
  def with_status_tag_search
    if params[:project_id].present?
      @tickets = Project.find(params[:project_id]).tickets
    end
    if params[:search_term].present?
      @tickets = @tickets.search_by_name_or_description(params[:search_term])
    end
    if params[:status].present?
      @tickets = @tickets.where(status: params[:status])
    end
    if params[:tag_id].present?
      @tickets = @tickets.joins(:tags).where("tags.id" => params[:tag_id])
    end
  end
end

app/helpers/tickets_helper.rb
module TicketsHelper
  def tag_list(ticket)
    if ticket.tags.any?
      ticket.tags.map(&:name).join(", ")
    else
      "-"
    end
  end
end

app/views/tickets/_form.html.erb
<%= render 'shared/errors', obj: @ticket %>

<div class='row'>
  <div class="col-sm-10">
    <%= bootstrap_form_for @ticket do |f| %>
      <%= f.collection_select :project_id, Project.all, :id, :name %>
      <%= f.text_field :name %>
      <%= f.text_area :body %>
      <%= f.select :status, options_for_ticket_status %>
      <%= f.collection_select :assignee_id, User.all, :id, :name, include_blank: "No one" %>
      <%= f.collection_check_boxes :tag_ids, Tag.alphabetical, :id, :name, inline: true, label_class: "checkbox", label: "Tags" do |cb| %>
        <% cb.label { cb.check_box + cb.text } %>
      <% end %>
      <%= f.form_group do %>
        <%= f.submit 'Submit', class: "btn btn-success" %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/tickets/_list.html.erb
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Assignee</th>
      <th>Status</th>
      <th>Tags</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% tickets.each do |ticket| %>
      <tr>
        <td><%= link_to ticket.name, ticket %></td>
        <td><%= ticket.assignee.try(:name) %></td>  <!--@ticket.assignee.name ? @ticket.assignee.name.name : nil-->
        <td><%= ticket.status.titleize %></td>
        <td><%= tag_list(ticket) %></td>
        <td class="shrink">
          <%= link_to 'Edit', edit_ticket_path(ticket) %>
          <%= link_to 'Destroy', ticket, method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/tickets/edit.html.erb
<h1>Editing Ticket</h1>

<%= render 'form' %>

<%= link_to 'Show', @ticket %> |
<%= link_to 'Back', tickets_path %>

app/views/tickets/index.html.erb
<h1>Tickets</h1>

<div class="ticket-filters">
  <%= form_tag tickets_path, method: :get do %>
    <p>
      Show tickets from 
      <%= select_tag :project_id, options_from_collection_for_select(Project.all, :id, :name, params[:project]), include_blank: "All Projects" %>
      with status
      <%= select_tag :status, options_for_ticket_status(params[:status]), include_blank: "Any Status" %>
      tagged
      <%= select_tag :tag_id, options_from_collection_for_select(Tag.alphabetical, :id, :name, params[:tag_id]), include_blank: "-" %>
      <br>
      with search
      <%= text_field_tag :search_term, '', placeholder: 'Search by title or description here' %>
      <%= button_tag "Update", class:"btn btn-primary" %>
      <span>
        <%= link_to "Clear Filters", tickets_path %>
      </span>
    </p>
  <% end %>
</div>

<br>

<% if @tickets.empty? %>
  <p class="empty-list">
    There are no tickets matching the selected filters.
    <%= link_to "Clear filters and show all tickets", tickets_path %>
  <p>
<% else %>
  <%= render "tickets/list", tickets: @tickets %>
<% end %>

<br>

<%= link_to 'New Ticket', new_ticket_path %>

app/views/tickets/new.html.erb
<h1>New Ticket</h1>

<%= render 'form' %>

<%= link_to 'Back', tickets_path %>

app/views/tickets/show.html.erb
<h1>
  <%= @ticket.name %>
</h1>

<p>
  <%= @ticket.body %>
</p>

<p>
  <strong>Tags:</strong>
  <%= tag_list(@ticket) %>
</p>

<br>

<%= link_to "Back", tickets_path %> |
<%= link_to 'Edit', edit_ticket_path(@ticket) %> |
<%= link_to 'Delete', @ticket, method: :delete, data: { confirm: 'Are you sure?' } %>

<table>
  <thead>
    <tr>
      <th>Status</th>
      <th>Creator</th>
      <th>Assignee</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= @ticket.status %></td>
      <td><%= @ticket.creator.name %></td>
      <td><%= @ticket.assignee ? @ticket.assignee.name : "-" %></td>
    </tr>
  </tbody>
</table>

<div class="comments">
  <h2>Comments</h2>
  
  <% if @ticket.comments.any? %>
    <% @ticket.reload.comments.each do |comment| %>
      <div class="comment">
        <p><%= comment.body %></p>
        <p>
          <em>
            posted by <%= comment.creator.name %> <%= time_ago_in_words(comment.created_at) %> ago
            <% if comment.created_at != comment.updated_at %>
              - updated <%= time_ago_in_words(comment.updated_at) %> ago
            <% end %>
          </em>
        </p>
        <% if signed_in? && current_user == comment.creator %>
          <p>
            <%= link_to "Edit", edit_ticket_comment_path(@ticket, comment), {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window'} %>
            <%= link_to 'Delete', ticket_comment_path(@ticket, comment), method: :delete, data: { confirm: 'Are you sure?' } %>
          </p>
        <% end %>
      </div>
    <% end %>
  <% else %>
    <p>There are no comments yet.</p>
  <% end %>
  
  <%= render "comments/form" %>
</div>

<div id="modal-window" class="modal fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
</div>