config/routes.rb
Rails.application.routes.draw do
  root to: "projects#index"
  
  get '/signup', to: 'users#new'
  get '/sign_in', to: 'sessions#new'
  post '/sign_in', to: 'sessions#create'
  get '/sign_out', to: 'sessions#destroy'
  
  resources :projects
  
  resources :tickets do
    resources :comments, only: [:create, :edit, :update, :destroy]
  end
  
  resources :tags, only: [:index, :new, :edit, :create, :update, :destroy]
  
  resources :users, only: [:index, :create] 
end

app/models/project.rb
class Project < ApplicationRecord
  validates :name, presence: true
  has_many :tickets, dependent: :destroy
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:show, :index]
  
  def index
    # display the Projects index to avoid any N+1 queries
    @projects = Project.includes(:tickets)
  end
  
  def show
  end
  
  def new
    @project = Project.new
  end
  
  def create
    @project = Project.new(project_params)
    
    if @project.save
      redirect_to @project
      flash[:success] = "Project was successfully created."
    else
      render :new
    end
  end
  
  def edit
  end
  
  def update
    if @project.update(project_params)
      redirect_to @project
      flash[:success] = "Project was successfully updated.."
    else
      render :edit
    end
  end
  
  def destroy
    @project.destroy
    redirect_to projects_path
    flash[:success] = "Project was successfully deleted."
  end
  
  private 
  
  def set_project
    @project = Project.find(params[:id])
  end
  
  def project_params
    params.require(:project).permit(:name, :description)
  end
end

app/views/projects/_form.html.erb
<%= render 'shared/errors', obj: @project %>

<div class='row'>
  <div class="col-sm-10">
    <%= bootstrap_form_for @project do |f| %>
      <%= f.text_field :name %>
      <%= f.text_area :description %>
      <%= f.form_group do %>
        <%= f.submit 'Submit', class: "btn btn-success" %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<h1>Projects</h1>

<% if @projects.empty? %>
  <p class="empty-list">
    There are no projects!
    <%= link_to "Add one now?", new_project_path %>
  </p>
<% else %>

  <table class="table">
    <thead>
     <tr>
       <th scope="row">Name</th>
       <th>Open Tickets</th>
       <th>Total Tickets</th>
     </tr>
   </thead>
   
   <tbody>
     <% @projects.each do |project| %>
      <tr>
        <td>
          <strong><%= link_to project.name, project %></strong>
          <br>
          <%= project.description %>
        </td>
        <td><%= project.tickets.open.count %></td>
        <td><%= project.tickets.count %></td>
       </tr>
     <% end %>
   </tbody>
  </table>

  <br>
  
  <%= link_to 'New Project', new_project_path %>
  
<% end %>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form' %>

<%= link_to "Back", projects_path %>

app/views/projects/show.html.erb
<h1>
  <%= @project.name %>
</h1>

<p>
  <%= @project.description %>
</p>

<p>
  <%= link_to 'Edit', edit_project_path(@project) %> |
  <%= link_to 'Delete', @project, method: :delete, data: { confirm: 'Are you sure?' } %>
</p>

<br>

<h2>Tickets</h2>

<%= render "tickets/list", tickets: @project.tickets %>