config/routes.rb
Rails.application.routes.draw do
  root to: "projects#index"
  
  get '/signup', to: 'users#new'
  get '/sign_in', to: 'sessions#new'
  post '/sign_in', to: 'sessions#create'
  get '/sign_out', to: 'sessions#destroy'
  
  resources :projects
  
  resources :tickets do
    resources :comments, only: [:create, :edit, :update, :destroy]
  end
  
  resources :tags, only: [:index, :new, :edit, :create, :update, :destroy]
  
  resources :users, only: [:index, :create] 
end

app/models/tag.rb
class Tag < ApplicationRecord
  scope :alphabetical, -> { order("tags.name ASC") }
  
  scope :with_counts, -> {
    joins("LEFT JOIN taggings ON taggings.tag_id = tags.id").select("tags.*, COUNT(taggings.id)").
      group("tags.id")
  }
  
  validates :name, presence: true
  
  has_many :taggings, dependent: :destroy
  has_many :tickets, through: :taggings
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: [:edit, :update, :destroy]
  before_action :require_user, except: [:show, :index]
  
  def index
    @tags = Tag.with_counts.alphabetical
  end
  
  def new
    @tag = Tag.new
  end
  
  def create
    @tag = Tag.new(tag_params)
    
    if @tag.save
      redirect_to tags_path
      flash[:success] = "Tag was successfully created."
    else
      render :new
    end
  end
  
  def edit
  end
  
  def update
    if @tag.update(tag_params)
      redirect_to tags_path
      flash[:success] = "Tag was successfully updated.."
    else
      render :edit
    end
  end
  
  def destroy
    @tag.destroy
    redirect_to tags_path
    flash[:success] = "Tag was successfully deleted."
  end
  
  private
  
  def set_tag
    @tag = Tag.find(params[:id])
  end
  
  def tag_params
    params.require(:tag).permit(:name)
  end
end

app/views/tags/_form.html.erb
<%= render 'shared/errors', obj: @tag %>

<div class='row'>
  <div class="col-sm-10">
    <%= bootstrap_form_for @tag do |f| %>
      <%= f.text_field :name %>
      <%= f.form_group do %>
        <%= f.submit 'Submit', class: "btn btn-success" %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/tags/edit.html.erb
<h1>Editing Tag</h1>

<%= render 'form' %>

<%= link_to 'Back', tags_path %>

app/views/tags/index.html.erb
<h1>Tags</h1>

<% if @tags.empty? %>
  <p class="empty-list">
    There are no tags!
    <%= link_to "Add one now?", new_tag_path %>
  </p>
<% else %>

  <table class="table">
    <thead>
     <tr>
       <th scope="row">Name</th>
       <th>Tickets</th>
       <th colspan="2"></th>
     </tr>
   </thead>
   
   <tbody>
     <% @tags.each do |tag| %>
      <tr>
        <td><%= tag.name %></td>
        <td><%= link_to tag.tickets.size, tickets_path(tag_id: tag.id) %></td>
        <td class="shrink">
          <%= link_to 'Edit', edit_tag_path(tag) %>
          or 
          <%= link_to 'Destroy', tag, method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
       </tr>
     <% end %>
   </tbody>
  </table>
  
  <br>
  
  <%= link_to 'New Tag', new_tag_path %>
<% end %>

app/views/tags/new.html.erb
<h1>New Tag</h1>

<%= render 'form' %>

<%= link_to "Back", tags_path %>