config/routes.rb
Rails.application.routes.draw do
  root to: "projects#index"
  
  get '/signup', to: 'users#new'
  get '/sign_in', to: 'sessions#new'
  post '/sign_in', to: 'sessions#create'
  get '/sign_out', to: 'sessions#destroy'
  
  resources :projects
  
  resources :tickets do
    resources :comments, only: [:create, :edit, :update, :destroy]
  end
  
  resources :tags, only: [:index, :new, :edit, :create, :update, :destroy]
  
  resources :users, only: [:index, :create] 
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="strong"><%= link_to "Ticketing", root_path %></li>
        <li><%= link_to "Projects", projects_path %></li>
        <li><%= link_to "Tickets", tickets_path %></li>
        <li><%= link_to "Tags", tags_path %></li>
        <li><%= link_to "Users", users_path %></li>
      </ul>
      
      <ul class="nav navbar-nav navbar-right">
        <% if signed_in? %>
         <li><p>Sign in as <%= current_user.name %></p></li>
         <li><%= link_to "Sign Out", '/sign_out' %></li>
        <% else %>
          <li><%= link_to 'Sign In', sign_in_path %></li> 
          <li><p> | </p></li>
          <li><%= link_to "Sign Up", signup_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Flo Ticketing</title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <header>
      <%= render 'layouts/header' %>
    </header>
    <div class="container">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
  </body>
</html>